---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: github

outputs:
  - name: build-output

run:
  path: github/ci/build.sh
